steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/defensoria-middleware:test-manual', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/defensoria-middleware:test-manual']

  # Deploy container image to Cloud Run (prod)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'defensoria-middleware-prod'
      - '--image'
      - 'gcr.io/$PROJECT_ID/defensoria-middleware:test-manual'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'APP_ENV=production'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/defensoria-middleware:test-manual'

options:
  logging: CLOUD_LOGGING_ONLY