steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/defensoria-middleware:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/defensoria-middleware:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'defensoria-middleware-prod'
      - '--image'
      - 'gcr.io/$PROJECT_ID/defensoria-middleware:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--execution-environment'
      - 'gen2'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - 'sat-defensoriapueblo:us-central1:defensoria-db'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '900'
      - '--cpu-boost'

images:
  - 'gcr.io/$PROJECT_ID/defensoria-middleware:latest'

options:
  logging: CLOUD_LOGGING_ONLY
