BEGIN;

SET search_path TO sds;

CREATE TABLE IF NOT EXISTS sds.historial_senal
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_senal_detectada smallint NOT NULL,
    usuario_id integer,
    accion text NOT NULL,
    descripcion text,
    estado_anterior text,
    estado_nuevo text,
    datos_adicionales text,
    fecha_registro timestamp with time zone DEFAULT NOW(),
    ip_address text,
    PRIMARY KEY (id),
    CONSTRAINT fk_historial_senal_detectada FOREIGN KEY (id_senal_detectada)
    REFERENCES sds.senal_detectada (id_senal_detectada)
);

COMMIT;
